// === TYPES ===
// Scenario data model for the Scenario Trainer feature.
// Used by: app/scenarios/page.tsx, components/ScenarioPlayer.tsx

export type ScenarioCategory =
  | 'preflop-opening'
  | 'facing-raise'
  | 'value-bet'
  | 'draw-play'
  | 'bluff'
  | 'bet-sizing'
  | 'multi-way'
  | 'position';

export type OptionQuality = 'best' | 'acceptable' | 'mistake' | 'disaster';

export type Difficulty = 'beginner' | 'intermediate' | 'advanced';

export interface ScenarioOption {
  action: string;
  quality: OptionQuality;
  explanation: string;
}

export interface Scenario {
  id: string;
  category: ScenarioCategory;
  difficulty: Difficulty;
  title: string;
  description: string;
  position: string;
  holeCards: string;
  board?: string;
  potSize?: number;
  betToCall?: number;
  numPlayers: number;
  actionHistory?: string;
  options: ScenarioOption[];
  homeGameTip?: string;
  isHomeGame?: boolean;
}

// === CATEGORY METADATA ===

export const SCENARIO_CATEGORIES: Record<ScenarioCategory, { label: string; icon: string; description: string }> = {
  'preflop-opening': {
    label: 'Apertura Preflop',
    icon: '🎯',
    description: 'Selezione mani e sizing di apertura',
  },
  'facing-raise': {
    label: 'Contro un Raise',
    icon: '⚔️',
    description: 'Decisioni di 3-bet, call o fold',
  },
  'value-bet': {
    label: 'Value Bet',
    icon: '💰',
    description: 'Quando e quanto puntare per valore',
  },
  'draw-play': {
    label: 'Gioco con Draw',
    icon: '🎨',
    description: 'Flush draw, scala, pot odds',
  },
  'bluff': {
    label: 'Bluff',
    icon: '🎭',
    description: 'C-bet bluff, semi-bluff, river bluff',
  },
  'bet-sizing': {
    label: 'Bet Sizing',
    icon: '📏',
    description: 'Scegliere la dimensione giusta della puntata',
  },
  'multi-way': {
    label: 'Piatti Multi-way',
    icon: '👥',
    description: 'Adattamenti per piatti con 3+ giocatori',
  },
  'position': {
    label: 'Posizione',
    icon: '🧭',
    description: 'Giocare in e fuori posizione',
  },
};

// === SCENARIOS DATA ===

export const SCENARIOS: Scenario[] = [
  // =====================================================================
  // PREFLOP OPENING (10 scenarios)
  // =====================================================================
  {
    id: 'pf-open-01',
    category: 'preflop-opening',
    difficulty: 'beginner',
    title: 'Asso-Re in UTG',
    description: 'Sei il primo a parlare al tavolo 6-max. Hai AK offsuit. Blinds 1/2.',
    position: 'UTG',
    holeCards: 'A♠ K♥',
    numPlayers: 6,
    options: [
      { action: 'Raise a 3x (6)', quality: 'best', explanation: 'AKo e una mano premium. Aprire con un raise standard da UTG e la scelta corretta: costruisci il piatto e riduci il numero di avversari.' },
      { action: 'Raise a 5x (10)', quality: 'acceptable', explanation: 'Un raise oversize non e terribile con AK, ma spaventa le mani peggiori che vorresti chiamassero. Il sizing standard e migliore.' },
      { action: 'Limp (call 2)', quality: 'mistake', explanation: 'Limpare con AK e un errore: non costruisci il piatto e inviti mani speculative a entrare a basso costo.' },
      { action: 'Fold', quality: 'disaster', explanation: 'Foldare AK preflop senza pressione e un errore gravissimo. E una delle mani piu forti del poker.' },
    ],
  },
  {
    id: 'pf-open-02',
    category: 'preflop-opening',
    difficulty: 'beginner',
    title: 'Coppia di Due dal Button',
    description: 'Tutti foldano fino a te sul Button. Hai 22. Blinds 1/2.',
    position: 'BTN',
    holeCards: '2♣ 2♦',
    numPlayers: 6,
    actionHistory: 'Tutti fold fino a te',
    options: [
      { action: 'Raise a 2.5x (5)', quality: 'best', explanation: 'Dal Button con tutti fold davanti, 22 e un raise obbligatorio. Hai posizione e puoi vincere i blinds o centrare un set al flop.' },
      { action: 'Limp (call 2)', quality: 'mistake', explanation: 'Limpare dal Button e un segnale di debolezza. Perdi liniziativa e dai ai blind odds ottime per giocare contro di te.' },
      { action: 'Fold', quality: 'mistake', explanation: 'Foldare una coppia dal Button con tutti fold e troppo tight. Anche 22 ha equity sufficiente in questa situazione.' },
      { action: 'Raise a 5x (10)', quality: 'acceptable', explanation: 'Un raise oversize funziona ma non e ottimale: vuoi che i blind chiamino con mani peggiori, non spaventarli.' },
    ],
  },
  {
    id: 'pf-open-03',
    category: 'preflop-opening',
    difficulty: 'beginner',
    title: 'J-9 suited da MP',
    description: 'Tavolo 6-max, UTG folda. Sei in Middle Position con J9 suited. Blinds 1/2.',
    position: 'MP',
    holeCards: 'J♥ 9♥',
    numPlayers: 6,
    actionHistory: 'UTG fold',
    options: [
      { action: 'Raise a 2.5x (5)', quality: 'best', explanation: 'J9s e una buona mano di apertura da MP. Suited connectors con potenziale di colore e scala. Apri con un raise standard.' },
      { action: 'Fold', quality: 'acceptable', explanation: 'Un fold da MP non e terribile con J9s, specialmente se il tavolo e molto aggressivo. Ma in generale e un open profittevole.' },
      { action: 'Limp (call 2)', quality: 'mistake', explanation: 'Limpare con suited connectors sembra allettante ma e un errore: non prendi liniziativa e non sai dove ti trovi postflop.' },
      { action: 'Raise a 4x (8)', quality: 'acceptable', explanation: 'Un sizing piu grande non e ideale con una mano speculativa: vuoi un buon prezzo, non impegnare troppo preflop.' },
    ],
  },
  {
    id: 'pf-open-04',
    category: 'preflop-opening',
    difficulty: 'intermediate',
    title: 'K-5 offsuit da Cutoff',
    description: 'Tavolo 6-max, UTG e MP foldano. Sei in Cutoff con K5 offsuit. Blinds 1/2.',
    position: 'CO',
    holeCards: 'K♣ 5♦',
    numPlayers: 6,
    actionHistory: 'UTG fold, MP fold',
    options: [
      { action: 'Raise a 2.5x (5)', quality: 'best', explanation: 'K5o e un open profittevole dal CO con due giocatori gia fuori. Hai posizione su BTN e blinds, e la K alta puo vincere piatti uncontested.' },
      { action: 'Fold', quality: 'acceptable', explanation: 'Foldare K5o non e un errore grave, ma stai lasciando profitto sul tavolo. Dal CO dovresti aprire un range piu ampio.' },
      { action: 'Limp (call 2)', quality: 'mistake', explanation: 'Come sempre, limpare mostra debolezza e invita raise dai giocatori dietro di te. Apri o folda, mai limpare.' },
    ],
    homeGameTip: 'Nei home game con giocatori che chiamano troppo, K5o dal CO diventa meno profittevole. Se i blind non foldano mai, puoi tightenarti.',
    isHomeGame: false,
  },
  {
    id: 'pf-open-05',
    category: 'preflop-opening',
    difficulty: 'beginner',
    title: 'Coppia di Assi da BB',
    description: 'Tutti limpano fino a te nel Big Blind. Hai AA. 4 giocatori nel piatto. Blinds 1/2.',
    position: 'BB',
    holeCards: 'A♠ A♣',
    numPlayers: 6,
    potSize: 9,
    actionHistory: 'UTG limpa, MP limpa, CO limpa, BTN limpa',
    options: [
      { action: 'Raise a 5x + 1x per limper (14)', quality: 'best', explanation: 'Con AA in un piatto limpato devi sempre raisare! Il sizing deve essere grande perche ci sono gia 4 limper. Formula: 3x + 1 per ogni limper funziona bene.' },
      { action: 'Raise a 3x (6)', quality: 'mistake', explanation: 'Un raise troppo piccolo da troppo buon prezzo ai limper. Con 4 giocatori gia dentro, 3x e insufficiente: verranno tutti e perdi il vantaggio.' },
      { action: 'Check', quality: 'disaster', explanation: 'DISASTRO! Checkare AA in un piatto limpato e il peggior errore possibile. Giocherai un piatto multi-way senza iniziativa. AA perde valore con tanti avversari.' },
      { action: 'All-in', quality: 'acceptable', explanation: 'Un all-in sembra estremo ma non e terribile: potresti ottenere una chiamata da un giocatore con una mano forte. Pero il raise grande e piu profittevole a lungo termine.' },
    ],
    homeGameTip: 'Nei home game i limper chiamano quasi tutto: qui puoi raisare anche piu grande, 6-7x + limper. Non avere paura di puntare grosso con AA!',
    isHomeGame: true,
  },
  {
    id: 'pf-open-06',
    category: 'preflop-opening',
    difficulty: 'intermediate',
    title: 'Q-J suited dallo Small Blind',
    description: 'Tavolo 6-max. Tutti foldano fino a te nello SB. Hai QJs. Blinds 1/2.',
    position: 'SB',
    holeCards: 'Q♠ J♠',
    numPlayers: 6,
    actionHistory: 'Tutti fold fino a te',
    options: [
      { action: 'Raise a 3x (6)', quality: 'best', explanation: 'QJs e una mano forte per rubare i blinds. Dal SB contro il solo BB, apri con un raise standard. Hai una mano con buona giocabilita postflop.' },
      { action: 'Limp (call 1 in piu)', quality: 'acceptable', explanation: 'Alcuni giocatori limpano dallo SB in situazione SB vs BB. Non e terribile con QJs perche ha buona giocabilita, ma il raise e piu profittevole.' },
      { action: 'Fold', quality: 'disaster', explanation: 'Foldare QJs dallo SB heads-up contro il BB e buttare soldi. E una mano troppo forte per non giocarla in questa situazione.' },
    ],
  },
  {
    id: 'pf-open-07',
    category: 'preflop-opening',
    difficulty: 'intermediate',
    title: 'Apertura con 7-6 suited',
    description: 'Tavolo 9-max. Sei in MP2 con 76 suited. 2 giocatori gia foldati. Blinds 1/2.',
    position: 'MP',
    holeCards: '7♥ 6♥',
    numPlayers: 9,
    actionHistory: 'UTG fold, UTG+1 fold',
    options: [
      { action: 'Fold', quality: 'best', explanation: 'Al tavolo 9-max, 76s da MP e troppo speculativa. Ci sono ancora troppi giocatori dietro che possono avere mani forti. Il range di apertura da MP/9-max deve essere tight.' },
      { action: 'Raise a 2.5x (5)', quality: 'acceptable', explanation: 'Aprire 76s da MP non e terribile se il tavolo e passivo, ma e al limite del range. Contro avversari aggressivi dietro rischi un 3-bet.' },
      { action: 'Limp (call 2)', quality: 'mistake', explanation: 'Limpare al tavolo 9-max invita raise e ti mette in una posizione scomoda con una mano marginale. O apri o foldi.' },
    ],
  },
  {
    id: 'pf-open-08',
    category: 'preflop-opening',
    difficulty: 'beginner',
    title: 'Coppia di Dieci dal BTN',
    description: 'Tavolo 6-max. UTG e MP foldano. CO apre a 5. Sei sul BTN con TT. Blinds 1/2.',
    position: 'BTN',
    holeCards: 'T♠ T♣',
    numPlayers: 6,
    actionHistory: 'UTG fold, MP fold, CO raise a 5',
    options: [
      { action: '3-bet a 14', quality: 'best', explanation: 'TT e abbastanza forte per un 3-bet contro un open dal CO. Il 3-bet ti da iniziativa e posizione, e scopri subito se il CO ha una mano forte.' },
      { action: 'Call 5', quality: 'acceptable', explanation: 'Callare con TT in posizione e accettabile: giocherai postflop con posizione e una buona mano. Pero il 3-bet e piu profittevole perche puoi vincere preflop.' },
      { action: 'Fold', quality: 'disaster', explanation: 'Foldare TT sul BTN contro un open dal CO e un errore enorme. E una mano nel top 5% di tutte le mani.' },
    ],
  },
  {
    id: 'pf-open-09',
    category: 'preflop-opening',
    difficulty: 'advanced',
    title: 'A-5 suited da UTG al 6-max',
    description: 'Sei UTG al tavolo 6-max con A5 suited. Blinds 1/2. Stack 100bb.',
    position: 'UTG',
    holeCards: 'A♦ 5♦',
    numPlayers: 6,
    options: [
      { action: 'Raise a 2.5x (5)', quality: 'best', explanation: 'A5s e un open standard da UTG al 6-max. LAce ti da bloccante verso AA e AK, il suited ti da potenziale colore. E nel range di apertura ottimale.' },
      { action: 'Fold', quality: 'acceptable', explanation: 'Un fold non e terribile: A5s e al limite del range UTG. Se non sei sicuro, foldare e ok. Ma nel range GTO e un open.' },
      { action: 'Limp', quality: 'mistake', explanation: 'Come sempre, limpare da UTG e un errore. Segnala debolezza e perdi liniziativa.' },
    ],
  },
  {
    id: 'pf-open-10',
    category: 'preflop-opening',
    difficulty: 'beginner',
    title: 'K-Q offsuit dal CO',
    description: 'Tavolo 6-max. UTG e MP foldano. Sei in CO con KQo. Blinds 1/2.',
    position: 'CO',
    holeCards: 'K♥ Q♣',
    numPlayers: 6,
    actionHistory: 'UTG fold, MP fold',
    options: [
      { action: 'Raise a 2.5x (5)', quality: 'best', explanation: 'KQo dal CO e un open chiarissimo. E una mano forte con buona giocabilita. Apri e gioca in posizione contro i blinds.' },
      { action: 'Raise a 4x (8)', quality: 'acceptable', explanation: 'Un sizing piu grande funziona ma non e ottimale: con una mano forte ma non premium, preferisci un sizing standard.' },
      { action: 'Fold', quality: 'disaster', explanation: 'Foldare KQo dal CO dopo due fold e un errore grave. E ben dentro il range di apertura da qualsiasi posizione.' },
    ],
    homeGameTip: 'KQ nei home game e oro: molti giocatori chiamano con K-basso o Q-basso e ti pagano quando colpisci top pair.',
    isHomeGame: true,
  },

  // =====================================================================
  // FACING RAISE (8 scenarios)
  // =====================================================================
  {
    id: 'fr-01',
    category: 'facing-raise',
    difficulty: 'beginner',
    title: 'AK contro un raise da UTG',
    description: 'UTG apre a 3x. Sei in MP con AKs. Blinds 1/2. Stack 100bb.',
    position: 'MP',
    holeCards: 'A♠ K♠',
    numPlayers: 6,
    actionHistory: 'UTG raise a 6',
    betToCall: 6,
    options: [
      { action: '3-bet a 18', quality: 'best', explanation: 'AKs e una mano da 3-bet automatico. Il 3-bet costruisce il piatto con una mano premium e ti da informazioni sulla forza del range di UTG.' },
      { action: 'Call 6', quality: 'acceptable', explanation: 'Callare con AKs e accettabile per variare il tuo gioco, ma il 3-bet e generalmente migliore perche hai una mano che vuole giocare per stack grosse.' },
      { action: 'Fold', quality: 'disaster', explanation: 'Foldare AKs contro un raise e inconcepibile. E la 5a mano piu forte del poker preflop.' },
    ],
  },
  {
    id: 'fr-02',
    category: 'facing-raise',
    difficulty: 'beginner',
    title: 'Coppia di Sei contro raise dal CO',
    description: 'CO apre a 2.5x. Sei sul BTN con 66. Blinds 1/2. Stack 100bb.',
    position: 'BTN',
    holeCards: '6♣ 6♠',
    numPlayers: 6,
    actionHistory: 'Fold, fold, CO raise a 5',
    betToCall: 5,
    options: [
      { action: 'Call 5', quality: 'best', explanation: 'Call e la scelta migliore con 66 in posizione. Hai set value implicito: se colpisci un set al flop, puoi vincere un piatto grosso. In posizione puoi gestire bene il postflop.' },
      { action: '3-bet a 14', quality: 'acceptable', explanation: 'Un 3-bet leggero con 66 non e terribile per variare il tuo range, ma rischi di trovarti in difficolta se vieni 4-bettato. Il call e piu sicuro e profittevole.' },
      { action: 'Fold', quality: 'mistake', explanation: 'Foldare 66 sul BTN con buone odds implicite per il set e troppo tight. Hai posizione e stack profondi, condizioni ideali per set mining.' },
    ],
  },
  {
    id: 'fr-03',
    category: 'facing-raise',
    difficulty: 'intermediate',
    title: 'J-10 suited contro raise da UTG',
    description: 'UTG apre a 3x al tavolo 6-max. Sei in CO con JTs. Blinds 1/2. Stack 100bb.',
    position: 'CO',
    holeCards: 'J♦ T♦',
    numPlayers: 6,
    actionHistory: 'UTG raise a 6',
    betToCall: 6,
    options: [
      { action: 'Call 6', quality: 'best', explanation: 'JTs e una buona mano per callare in posizione contro UTG. Hai potenziale di scala, colore e due paia. La posizione ti permette di giocare bene postflop.' },
      { action: 'Fold', quality: 'acceptable', explanation: 'Un fold non e un errore: UTG ha un range forte e JTs potrebbe essere dominata. Ma con posizione e stack profondi, il call e profittevole.' },
      { action: '3-bet a 18', quality: 'mistake', explanation: 'Un 3-bet con JTs contro UTG e rischioso: se UTG 4-betta devi foldare, e il suo range di call al 3-bet ti domina spesso. Meglio callare in posizione.' },
    ],
    homeGameTip: 'Nei home game JTs e fantastica da callare: colpisci tanti draw e i giocatori loose ti pagano quando completi.',
    isHomeGame: true,
  },
  {
    id: 'fr-04',
    category: 'facing-raise',
    difficulty: 'intermediate',
    title: 'A-J offsuit contro 3-bet',
    description: 'Apri dal CO a 2.5x. Il BTN 3-betta a 8x. Blinds fold. Hai AJo. Blinds 1/2.',
    position: 'CO',
    holeCards: 'A♣ J♥',
    numPlayers: 6,
    potSize: 19,
    actionHistory: 'CO (tu) raise a 5, BTN 3-bet a 16',
    betToCall: 11,
    options: [
      { action: 'Fold', quality: 'best', explanation: 'AJo contro un 3-bet dal BTN e una mano da fold. Sei dominato da AK e AQ che sono nel suo range di 3-bet, e non hai posizione postflop se chiami.' },
      { action: 'Call 11', quality: 'acceptable', explanation: 'Callare non e terribile ma ti mette in situazioni difficili postflop fuori posizione con una mano che spesso e dominata.' },
      { action: '4-bet a 36', quality: 'mistake', explanation: 'Un 4-bet con AJo e un bluff troppo costoso. Non hai bloccanti sufficienti e se vieni chiamato sei quasi sempre in svantaggio.' },
    ],
  },
  {
    id: 'fr-05',
    category: 'facing-raise',
    difficulty: 'advanced',
    title: 'Coppia di Re contro 4-bet',
    description: 'Apri dal CO, BTN 3-betta, tu 4-betti con KK, BTN va all-in per 100bb. Blinds 1/2.',
    position: 'CO',
    holeCards: 'K♠ K♥',
    numPlayers: 6,
    potSize: 50,
    actionHistory: 'Tu 4-bet, BTN shove all-in 100bb',
    betToCall: 70,
    options: [
      { action: 'Call all-in', quality: 'best', explanation: 'KK contro un 5-bet all-in e un call automatico. Lunica mano che ti batte e AA, e statisticamente hai circa 80% equity contro il suo range di shove.' },
      { action: 'Fold', quality: 'disaster', explanation: 'Foldare KK preflop dopo un 4-bet e quasi sempre sbagliato. Dovresti foldare KK preflop solo in tornei con situazioni ICM estreme.' },
    ],
  },
  {
    id: 'fr-06',
    category: 'facing-raise',
    difficulty: 'beginner',
    title: 'K-9 offsuit contro raise da UTG',
    description: 'UTG apre a 3x al tavolo 9-max. Sei in MP con K9o. Blinds 1/2.',
    position: 'MP',
    holeCards: 'K♦ 9♣',
    numPlayers: 9,
    actionHistory: 'UTG raise a 6',
    betToCall: 6,
    options: [
      { action: 'Fold', quality: 'best', explanation: 'K9o e troppo debole per chiamare un raise da UTG al 9-max. Sei probabilmente dominato da KQ, KJ, KT e coppie piu alte. Il fold e chiaro.' },
      { action: 'Call 6', quality: 'mistake', explanation: 'Callare con K9o fuori posizione contro un range forte e bruciare soldi. Quando colpisci K, sei spesso dominato dal kicker.' },
      { action: '3-bet a 18', quality: 'disaster', explanation: 'Un 3-bet con K9o contro UTG e un bluff suicida. UTG ha un range molto forte al 9-max e ti punira severamente.' },
    ],
    homeGameTip: 'Anche nei home game, K9o contro un raise da UTG e un fold. Non farti tentare dal K alto: il kicker 9 ti mettera sempre nei guai.',
    isHomeGame: true,
  },
  {
    id: 'fr-07',
    category: 'facing-raise',
    difficulty: 'advanced',
    title: 'A-5 suited come 3-bet bluff',
    description: 'CO apre a 2.5x. Sei sul BTN con A5s. Blinds 1/2. Stack 100bb. Il CO apre molto spesso.',
    position: 'BTN',
    holeCards: 'A♥ 5♥',
    numPlayers: 6,
    actionHistory: 'Fold fino a CO, CO raise a 5',
    betToCall: 5,
    options: [
      { action: '3-bet a 14', quality: 'best', explanation: 'A5s e il 3-bet bluff perfetto: hai il bloccante verso AA e A5, e se vieni chiamato hai buona giocabilita postflop con potenziale colore e ruota.' },
      { action: 'Call 5', quality: 'acceptable', explanation: 'Call in posizione e ok con A5s, ma perdi lopportunita di 3-bettare come bluff con una mano ideale per questo scopo.' },
      { action: 'Fold', quality: 'mistake', explanation: 'Foldare A5s sul BTN contro un open dal CO e troppo tight. Hai troppe cose a tuo favore: posizione, bloccante, giocabilita.' },
    ],
  },
  {
    id: 'fr-08',
    category: 'facing-raise',
    difficulty: 'intermediate',
    title: 'Q-Q nel Big Blind contro steal',
    description: 'Tutti foldano. BTN apre a 2.5x. SB folda. Hai QQ nel BB. Blinds 1/2.',
    position: 'BB',
    holeCards: 'Q♥ Q♦',
    numPlayers: 6,
    actionHistory: 'Fold fino a BTN, BTN raise a 5, SB fold',
    betToCall: 3,
    options: [
      { action: '3-bet a 14', quality: 'best', explanation: 'QQ e una mano premium: devi 3-bettare dal BB. Il BTN apre un range ampio, quindi la tua QQ domina gran parte delle sue mani. Costruisci il piatto!' },
      { action: 'Call 3', quality: 'acceptable', explanation: 'Trappare con QQ puo funzionare occasionalmente per ingannare lavversario, ma rinunci a costruire il piatto con una mano forte e giochi fuori posizione.' },
      { action: 'All-in', quality: 'mistake', explanation: 'All-in preflop con QQ contro un open dal BTN e troppo aggressivo: folda tutte le mani peggiori e chiama solo con quelle che ti battono (AA, KK).' },
    ],
  },

  // =====================================================================
  // VALUE BET (8 scenarios)
  // =====================================================================
  {
    id: 'vb-01',
    category: 'value-bet',
    difficulty: 'beginner',
    title: 'Top pair top kicker al flop',
    description: 'Hai aperto con AK dal CO, il BB ha chiamato. Flop: A-7-2 rainbow. BB checka. Piatto 13.',
    position: 'CO',
    holeCards: 'A♠ K♥',
    board: 'A♦ 7♣ 2♠',
    potSize: 13,
    numPlayers: 2,
    actionHistory: 'Tu apri, BB chiama. Flop: A-7-2. BB checka.',
    options: [
      { action: 'Bet 9 (circa 2/3 pot)', quality: 'best', explanation: 'Hai top pair top kicker su un board secco. Punta per valore! Le mani come A-piccolo, 77, pocket pair medie chiameranno. 2/3 pot e il sizing perfetto.' },
      { action: 'Bet 4 (circa 1/3 pot)', quality: 'acceptable', explanation: 'Una puntata piccola estrae comunque valore ma lascia soldi sul tavolo. Con TPTK puoi permetterti di puntare di piu.' },
      { action: 'Check', quality: 'mistake', explanation: 'Checkare TPTK su un board secco e un errore. Non stai estraendo valore dalle mani peggiori e dai una carta gratis.' },
    ],
    homeGameTip: 'Nei home game con calling station, puoi puntare anche 3/4 pot o pot intero. Ti chiameranno comunque con qualsiasi Asso!',
    isHomeGame: true,
  },
  {
    id: 'vb-02',
    category: 'value-bet',
    difficulty: 'intermediate',
    title: 'Set al turn su board connesso',
    description: 'Hai 88 e il board e 8-9-J-2 con due cuori. Sei in posizione. Piatto 40. Avversario checka.',
    position: 'BTN',
    holeCards: '8♠ 8♦',
    board: '8♣ 9♥ J♥ 2♣',
    potSize: 40,
    numPlayers: 2,
    actionHistory: 'Avversario checka al turn',
    options: [
      { action: 'Bet 30 (3/4 pot)', quality: 'best', explanation: 'Hai un set su un board con molti draw. DEVI puntare grosso per protezione e valore! Mani come J-x, 9-x, T-x, flush draw pagheranno.' },
      { action: 'Bet 15 (meno di 1/2 pot)', quality: 'mistake', explanation: 'Puntare poco su un board pericoloso e un errore: dai odds troppo buone ai draw. Se il flush o la scala si completano, perdi un piatto enorme.' },
      { action: 'Check', quality: 'disaster', explanation: 'Checkare un set su un board con draw e disastroso. Dai una carta gratis e rischi che il tuo avversario completi senza pagare.' },
      { action: 'All-in (overbet)', quality: 'acceptable', explanation: 'Un all-in puo funzionare se gli stack sono corti, ma rischi di far foldare mani che avrebbero chiamato un bet piu ragionevole.' },
    ],
  },
  {
    id: 'vb-03',
    category: 'value-bet',
    difficulty: 'intermediate',
    title: 'Due coppie al river',
    description: 'Hai KQ e il board e K-Q-5-8-3 rainbow. Piatto 60. Avversario checka al river.',
    position: 'CO',
    holeCards: 'K♣ Q♦',
    board: 'K♠ Q♥ 5♦ 8♣ 3♠',
    potSize: 60,
    numPlayers: 2,
    actionHistory: 'Bet al flop e turn, avversario ha chiamato entrambi. River 3. Avversario checka.',
    options: [
      { action: 'Bet 40 (2/3 pot)', quality: 'best', explanation: 'Due coppie su un board secco e una mano forte. Lavversario ha chiamato flop e turn, quindi ha qualcosa. Punta per valore contro K-x, Q-x, pocket pair.' },
      { action: 'Bet 20 (1/3 pot)', quality: 'acceptable', explanation: 'Una bet piccola estrae valore da mani deboli ma perdi valore contro mani come KJ o QJ che avrebbero chiamato di piu.' },
      { action: 'Check', quality: 'mistake', explanation: 'Checkare due coppie al river dopo che lavversario ha chiamato due strade e lasciare soldi sul tavolo. Quasi sempre ha qualcosa con cui puo chiamare.' },
    ],
    homeGameTip: 'Al home game dopo due call, lavversario ha quasi certamente un pezzo del board. Punta grosso senza paura!',
    isHomeGame: true,
  },
  {
    id: 'vb-04',
    category: 'value-bet',
    difficulty: 'beginner',
    title: 'Overpair al flop',
    description: 'Hai QQ. Board: 9-6-3 rainbow. Hai aperto e il BB ha chiamato. Piatto 12. BB checka.',
    position: 'BTN',
    holeCards: 'Q♠ Q♥',
    board: '9♣ 6♦ 3♠',
    potSize: 12,
    numPlayers: 2,
    actionHistory: 'Tu apri dal BTN, BB chiama. Flop: 9-6-3. BB checka.',
    options: [
      { action: 'Bet 8 (2/3 pot)', quality: 'best', explanation: 'QQ e un forte overpair su un board basso. Punta per valore: mani come 9-x, coppie medie, e anche gutshot chiameranno. Il sizing 2/3 pot e standard.' },
      { action: 'Bet 4 (1/3 pot)', quality: 'acceptable', explanation: 'Una bet piccola funziona per estrarre valore da mani deboli, ma con un overpair puoi permetterti un sizing piu grande.' },
      { action: 'Check', quality: 'mistake', explanation: 'Non checkare un overpair al flop! Perdi valore e dai una carta gratis che potrebbe battere la tua mano.' },
    ],
  },
  {
    id: 'vb-05',
    category: 'value-bet',
    difficulty: 'advanced',
    title: 'Thin value bet al river',
    description: 'Hai A9s. Board: A-K-4-7-2 rainbow. Piatto 50. Avversario checka al river. Hai puntato flop e checkato turn.',
    position: 'CO',
    holeCards: 'A♥ 9♥',
    board: 'A♣ K♦ 4♠ 7♣ 2♦',
    potSize: 50,
    numPlayers: 2,
    actionHistory: 'Bet al flop, check al turn, river 2. Avversario checka.',
    options: [
      { action: 'Bet 18 (circa 1/3 pot)', quality: 'best', explanation: 'Thin value bet! A9 batte tutte le coppie medie, 4-x, 7-x. Il sizing piccolo (1/3) e perfetto perche induci call da mani deboli senza rischiare troppo contro AK o AQ.' },
      { action: 'Check', quality: 'acceptable', explanation: 'Checkare non e un errore: il K sul board rende il range dellavversario potenzialmente forte. Ma perdi valore contro molte mani che chiameranno un bet piccolo.' },
      { action: 'Bet 35 (2/3 pot)', quality: 'mistake', explanation: 'Puntare grosso con A9 su un board con K e rischioso: fai foldare tutte le mani che batti e vieni chiamato solo da mani che ti battono.' },
    ],
  },
  {
    id: 'vb-06',
    category: 'value-bet',
    difficulty: 'beginner',
    title: 'Full house al river',
    description: 'Hai 77. Board: 7-A-3-A-K. Piatto 80. Avversario punta 40 al river.',
    position: 'BTN',
    holeCards: '7♦ 7♣',
    board: '7♠ A♥ 3♦ A♣ K♠',
    potSize: 80,
    betToCall: 40,
    numPlayers: 2,
    actionHistory: 'Check-call fino al river. River K. Avversario punta 40.',
    options: [
      { action: 'Raise a 110', quality: 'best', explanation: 'Hai un full house! Lavversario sta puntando per valore con A-x, K-x o trip. Un raise estrae il massimo valore. Non aver paura di raisare!' },
      { action: 'Call 40', quality: 'acceptable', explanation: 'Call e sicuro ma perdi molto valore. Quando hai il full, devi cercare di estrarre il massimo. Un raise qui e quasi sempre pagato.' },
      { action: 'All-in', quality: 'acceptable', explanation: 'All-in e aggressivo ma puo far foldare mani medie. Un raise piu contenuto potrebbe estrarre piu valore.' },
      { action: 'Fold', quality: 'disaster', explanation: 'Foldare un full house e impensabile. Perdi solo contro quad o full superiore, che sono estremamente rari.' },
    ],
    homeGameTip: 'Nei home game con full house, raisa sempre! I giocatori chiamano con qualsiasi Asso e non folderanno mai trip.',
    isHomeGame: true,
  },
  {
    id: 'vb-07',
    category: 'value-bet',
    difficulty: 'advanced',
    title: 'Value bet dopo check-raise al flop',
    description: 'Avversario apre, tu chiami con AT dal BB. Flop: A-8-3. Lavversario c-betta, tu check-raisi, lui chiama. Turn: 5. Piatto 55.',
    position: 'BB',
    holeCards: 'A♣ T♠',
    board: 'A♦ 8♣ 3♥ 5♠',
    potSize: 55,
    numPlayers: 2,
    actionHistory: 'Flop: avversario c-bet, tu check-raise, lui chiama. Turn: 5.',
    options: [
      { action: 'Bet 25 (circa 1/2 pot)', quality: 'best', explanation: 'Dopo il check-raise al flop, il turn brick e perfetto per continuare a puntare per valore. Il call del flop indica mani come A-piccolo, 88, gutshot. Sizing medio per non spaventare.' },
      { action: 'Bet 40 (3/4 pot)', quality: 'acceptable', explanation: 'Un bet piu grande funziona ancora per valore, ma rischi di far foldare mani marginali come A2-A5 che avrebbero chiamato un bet piu piccolo.' },
      { action: 'Check', quality: 'mistake', explanation: 'Checkare il turn dopo un check-raise e incoerente e rinuncia a valore. Lavversario ha mostrato forza chiamando, continuaci sopra.' },
    ],
  },
  {
    id: 'vb-08',
    category: 'value-bet',
    difficulty: 'intermediate',
    title: 'Top pair su board paired',
    description: 'Hai AQ. Board: Q-Q-7-2 rainbow. Piatto 35. Avversario checka al turn.',
    position: 'BTN',
    holeCards: 'A♠ Q♣',
    board: 'Q♦ Q♠ 7♣ 2♥',
    potSize: 35,
    numPlayers: 2,
    actionHistory: 'Tu apri, avversario chiama. Flop bet, avversario chiama. Turn 2. Avversario checka.',
    options: [
      { action: 'Bet 18 (circa 1/2 pot)', quality: 'best', explanation: 'Hai trip Q con kicker A. Punta per valore! Le mani come 7-x, pocket pair, K-high chiameranno. Il sizing medio massimizza il valore senza spaventare.' },
      { action: 'Check', quality: 'acceptable', explanation: 'Checkare per trappare e unidea, ma rischi che lavversario non punti al river se non ha nulla. Meglio estrarre valore ora.' },
      { action: 'Bet 30 (quasi pot)', quality: 'acceptable', explanation: 'Un bet grande rischia di far foldare mani deboli. Con trip, preferisci bet piccoli-medi per tenere dentro piu mani.' },
    ],
  },

  // =====================================================================
  // DRAW PLAY (6 scenarios)
  // =====================================================================
  {
    id: 'dp-01',
    category: 'draw-play',
    difficulty: 'beginner',
    title: 'Flush draw al flop',
    description: 'Hai A-5 di cuori. Flop: K-8-3 con due cuori. Avversario punta 10 nel piatto di 15.',
    position: 'BTN',
    holeCards: 'A♥ 5♥',
    board: 'K♥ 8♥ 3♦',
    potSize: 15,
    betToCall: 10,
    numPlayers: 2,
    actionHistory: 'Avversario punta 10',
    options: [
      { action: 'Call 10', quality: 'best', explanation: 'Hai 9 outs per il nut flush (35% circa con 2 carte). Le pot odds sono 10/(15+10) = 40%. Con le odds implicite (soldi che vincerai se colpisci), il call e chiaramente profittevole.' },
      { action: 'Raise a 28', quality: 'acceptable', explanation: 'Un semi-bluff raise puo funzionare: forzi fold da mani deboli e hai equity se chiamato. Ma il call semplice e meno rischioso e comunque profittevole.' },
      { action: 'Fold', quality: 'mistake', explanation: 'Con il nut flush draw hai troppa equity per foldare. 9 outs = circa 35% con 2 carte. Le pot odds + odds implicite rendono il call obbligatorio.' },
    ],
  },
  {
    id: 'dp-02',
    category: 'draw-play',
    difficulty: 'intermediate',
    title: 'Open-ended straight draw al turn',
    description: 'Hai 9-8. Board: 7-6-K-2. Turn appena uscito. Avversario punta 25 in un piatto di 40. Solo river rimasto.',
    position: 'CO',
    holeCards: '9♣ 8♣',
    board: '7♦ 6♠ K♥ 2♣',
    potSize: 40,
    betToCall: 25,
    numPlayers: 2,
    actionHistory: 'Avversario punta 25 al turn',
    options: [
      { action: 'Call 25', quality: 'acceptable', explanation: 'Hai 8 outs (4 cinque e 4 dieci) = circa 16% al river. Pot odds: 25/65 = 38%. Matematicamente e un fold, ma con le odds implicite (se colpisci puoi vincere molto) il call puo essere giustificato.' },
      { action: 'Fold', quality: 'best', explanation: 'Le pot odds sono 38% ma hai solo 16% equity. Senza odds implicite sufficienti, il fold e la scelta corretta. Al turn con 1 sola carta devi essere piu disciplinato.' },
      { action: 'Raise a 65', quality: 'mistake', explanation: 'Un raise come semi-bluff al turn e molto rischioso: se lavversario chiama, hai solo il 16% al river. E se re-raisa sei in grossi guai.' },
    ],
  },
  {
    id: 'dp-03',
    category: 'draw-play',
    difficulty: 'beginner',
    title: 'Flush draw + pair al flop',
    description: 'Hai Q-J di picche. Board: J-7-4 con due picche. Avversario punta 8 in un piatto di 12.',
    position: 'BTN',
    holeCards: 'Q♠ J♠',
    board: 'J♣ 7♠ 4♠',
    potSize: 12,
    betToCall: 8,
    numPlayers: 2,
    actionHistory: 'Avversario punta 8',
    options: [
      { action: 'Raise a 24', quality: 'best', explanation: 'Hai top pair + flush draw = circa 15 outs (54% equity). Questa e una mano da semi-bluff raise! Puoi vincere subito con il fold o hai tantissima equity se chiamato.' },
      { action: 'Call 8', quality: 'acceptable', explanation: 'Call e sicuro e profittevole con la tua equity enorme. Ma il raise e migliore perche puoi vincere il piatto immediatamente.' },
      { action: 'Fold', quality: 'disaster', explanation: 'Foldare top pair + nut flush draw e un errore enorme. Hai circa 54% equity contro quasi qualsiasi mano!' },
    ],
  },
  {
    id: 'dp-04',
    category: 'draw-play',
    difficulty: 'intermediate',
    title: 'Gutshot al turn in piatto grosso',
    description: 'Hai A-K. Board: Q-J-5-8. Turn appena uscito. Avversario punta 30 in un piatto di 60.',
    position: 'CO',
    holeCards: 'A♣ K♦',
    board: 'Q♥ J♣ 5♦ 8♠',
    potSize: 60,
    betToCall: 30,
    numPlayers: 2,
    actionHistory: 'Avversario punta 30 al turn',
    options: [
      { action: 'Call 30', quality: 'acceptable', explanation: 'Hai 4 outs per la scala (qualsiasi T) + 6 outs per top pair (3 A + 3 K) = circa 10 outs = 20% al river. Pot odds: 30/90 = 33%. Marginal ma con odds implicite enormi quando colpisci scala, il call ha senso.' },
      { action: 'Fold', quality: 'best', explanation: 'Pot odds 33% con solo 20% equity diretta. Il fold e la scelta matematicamente corretta. Anche con overcards, rischi di fare top pair e perdere comunque contro set o due coppie.' },
      { action: 'Raise a 80', quality: 'mistake', explanation: 'Un raise come bluff qui e troppo costoso. Lavversario ha puntato grosso e probabilmente ha una mano forte. Il rischio non vale.' },
    ],
    homeGameTip: 'Nei home game se conosci lavversario come calling station, puoi foldare piu tranquillamente: non ti pagheranno quando colpisci con un raise perche... aspetta, loro chiamano sempre! In realta il call diventa migliore.',
    isHomeGame: true,
  },
  {
    id: 'dp-05',
    category: 'draw-play',
    difficulty: 'advanced',
    title: 'Combo draw: flush + OESD',
    description: 'Hai 8-7 di cuori. Board: 6-9-A con due cuori. Flop in un piatto di 20. Avversario punta 15.',
    position: 'BB',
    holeCards: '8♥ 7♥',
    board: '6♥ 9♣ A♥',
    potSize: 20,
    betToCall: 15,
    numPlayers: 2,
    actionHistory: 'Avversario punta 15 al flop',
    options: [
      { action: 'Raise all-in', quality: 'best', explanation: 'Hai un MONSTER draw: flush draw (9 outs) + OESD (6 outs non gia contati) = circa 15 outs = 54% equity con 2 carte! Sei FAVORITO! Lo shove e la giocata migliore perche massimizzi la fold equity.' },
      { action: 'Call 15', quality: 'acceptable', explanation: 'Call e ok ma perdi la fold equity. Con 54% equity sei favorito, pero giocare il turn fuori posizione puo essere complicato se non colpisci.' },
      { action: 'Fold', quality: 'disaster', explanation: 'Foldare un combo draw con 54% equity e un errore enorme. Sei statisticamente il favorito in questa mano!' },
    ],
  },
  {
    id: 'dp-06',
    category: 'draw-play',
    difficulty: 'advanced',
    title: 'Backdoor draw al flop',
    description: 'Hai K-Q di picche. Board: A-T-3 con un solo picche. Avversario punta 6 in piatto di 10. Hai gutshot + backdoor flush.',
    position: 'BTN',
    holeCards: 'K♠ Q♠',
    board: 'A♦ T♠ 3♣',
    potSize: 10,
    betToCall: 6,
    numPlayers: 2,
    actionHistory: 'Avversario punta 6 al flop',
    options: [
      { action: 'Call 6', quality: 'best', explanation: 'Hai gutshot (4 J per la scala), 6 overcards parziali, e backdoor flush. Circa 10 outs effettivi. Le pot odds (6/16=37%) sono vicine alla tua equity e le odds implicite rendono il call profittevole.' },
      { action: 'Fold', quality: 'acceptable', explanation: 'Un fold non e terribile: la tua mano e debole al momento e potresti fare top pair e perdere contro A-x. Ma con posizione e draw multipli il call e preferibile.' },
      { action: 'Raise a 18', quality: 'acceptable', explanation: 'Un semi-bluff raise in posizione funziona se lavversario puo foldare A-debole o mani come pocket pair. Rischioso ma non insensato.' },
    ],
  },

  // =====================================================================
  // BLUFF (6 scenarios)
  // =====================================================================
  {
    id: 'bl-01',
    category: 'bluff',
    difficulty: 'beginner',
    title: 'C-bet bluff su board secco',
    description: 'Hai aperto con 9-8 suited dal CO. Solo il BB chiama. Flop: K-7-2 rainbow. BB checka. Piatto 11.',
    position: 'CO',
    holeCards: '9♦ 8♦',
    board: 'K♠ 7♣ 2♥',
    potSize: 11,
    numPlayers: 2,
    actionHistory: 'Tu apri, BB chiama. Flop: K-7-2 rainbow. BB checka.',
    options: [
      { action: 'Bet 4 (circa 1/3 pot)', quality: 'best', explanation: 'C-bet bluff su un board secco e una giocata standard. Il board K-7-2 favorisce il tuo range di apertura (hai piu K). Un bet piccolo e sufficiente per far foldare mani come A-basso, coppie piccole.' },
      { action: 'Check', quality: 'acceptable', explanation: 'Checkare non e terribile: puoi provare a migliorare al turn. Ma un c-bet piccolo su questo board e molto profittevole perche il BB foldera spesso.' },
      { action: 'Bet 9 (quasi pot)', quality: 'mistake', explanation: 'Un bet grande come bluff su questo board rischia troppo. Il bet piccolo ottiene lo stesso effetto (fold dalle mani deboli) rischiando meno.' },
    ],
  },
  {
    id: 'bl-02',
    category: 'bluff',
    difficulty: 'intermediate',
    title: 'Doppio barile bluff al turn',
    description: 'Hai c-bettato al flop con A-5 suited (niente) e sei stato chiamato. Turn: J, che completa un possibile straight. Board: Q-T-3-J. Piatto 28.',
    position: 'BTN',
    holeCards: 'A♦ 5♦',
    board: 'Q♠ T♣ 3♥ J♦',
    potSize: 28,
    numPlayers: 2,
    actionHistory: 'Tu c-bet al flop, avversario chiama. Turn: J. Avversario checka.',
    options: [
      { action: 'Bet 18 (circa 2/3 pot)', quality: 'best', explanation: 'La J al turn e una scare card perfetta per bluffare: rappresenti AK per la scala. Lavversario con mani come coppia piccola o T-x avra paura della scala e foldera spesso.' },
      { action: 'Check', quality: 'acceptable', explanation: 'Checkare e rinunciare e ok, ma perdi unopportunita di bluff perfetta. La J cambia tutto il board e il tuo avversario lo sa.' },
      { action: 'Bet 8 (circa 1/3 pot)', quality: 'mistake', explanation: 'Se bluffi, devi puntare abbastanza da far foldare. Un bet piccolo da odds troppo buone allavversario per chiamare con coppia.' },
    ],
  },
  {
    id: 'bl-03',
    category: 'bluff',
    difficulty: 'advanced',
    title: 'River bluff su missed flush draw',
    description: 'Avevi il flush draw che non si e completato. Board: K-8-4-2-J (niente flush). Piatto 50. Avversario checka al river.',
    position: 'BTN',
    holeCards: 'T♠ 9♠',
    board: 'K♠ 8♠ 4♥ 2♦ J♣',
    potSize: 50,
    numPlayers: 2,
    actionHistory: 'Hai puntato flop e turn come semi-bluff. River: J (flush mancato). Avversario checka.',
    options: [
      { action: 'Bet 35 (2/3 pot)', quality: 'best', explanation: 'Il river bluff qui e forte: hai puntato due strade mostrando forza. La J al river e una scare card. Lavversario con coppia media foldera spesso, soprattutto se teme K-J o J-J.' },
      { action: 'Check', quality: 'acceptable', explanation: 'Arrendersi e ok. Il river bluff e ad alto rischio. Se lavversario ha K-x potrebbe chiamare. Dipende dalla tua lettura.' },
      { action: 'Bet 15 (1/3 pot)', quality: 'mistake', explanation: 'Un bet piccolo al river come bluff non funziona: da odds troppo buone. Lavversario chiamera con qualsiasi coppia. Se bluffi, punta abbastanza.' },
    ],
  },
  {
    id: 'bl-04',
    category: 'bluff',
    difficulty: 'beginner',
    title: 'C-bet su board basso',
    description: 'Apri con AQ dal BTN. BB chiama. Flop: 5-4-2 rainbow. BB checka. Piatto 11.',
    position: 'BTN',
    holeCards: 'A♣ Q♥',
    board: '5♦ 4♣ 2♠',
    potSize: 11,
    numPlayers: 2,
    actionHistory: 'Tu apri dal BTN, BB chiama. Flop: 5-4-2. BB checka.',
    options: [
      { action: 'Bet 4 (1/3 pot)', quality: 'best', explanation: 'Anche se non hai colpito, hai 6 overcards come outs. Un c-bet piccolo su un board basso e quasi automatico: il BB non ha colpito spesso e foldera con A-alto, K-alto.' },
      { action: 'Check', quality: 'acceptable', explanation: 'Check e ok: hai 6 outs per top pair e il board non e pericoloso. Ma il c-bet piccolo e piu profittevole a lungo termine.' },
      { action: 'Bet 10 (quasi pot)', quality: 'mistake', explanation: 'Troppo grosso per un bluff su un board basso. Il bet piccolo funziona altrettanto bene e rischi molto meno.' },
    ],
    homeGameTip: 'Nei home game, attenzione al c-bet su board bassi: i giocatori loose spesso hanno mani come 5-3, 4-3 che al tavolo "serio" non giocherebbero. Piu cautela!',
    isHomeGame: true,
  },
  {
    id: 'bl-05',
    category: 'bluff',
    difficulty: 'advanced',
    title: 'Bluff overbet al river',
    description: 'Il board e A-K-Q-8-3. Non hai niente (6-5). Hai rappresentato forza tutta la mano. Piatto 80. Avversario checka.',
    position: 'BTN',
    holeCards: '6♣ 5♣',
    board: 'A♠ K♥ Q♦ 8♣ 3♦',
    potSize: 80,
    numPlayers: 2,
    actionHistory: 'Hai puntato a ogni street. River: 3. Avversario checka.',
    options: [
      { action: 'Bet 70 (quasi pot)', quality: 'best', explanation: 'Questo e il momento perfetto per un bluff grande. Hai rappresentato A-K, A-Q, o KQ tutta la mano. Lavversario con mani come J-J, T-T, o A debole foldera sotto pressione.' },
      { action: 'Check (arrendersi)', quality: 'acceptable', explanation: 'Arrendersi con 6 high e ragionevole. Ma se hai gia investito in questa linea di bluff, il river e dove raccogli i frutti.' },
      { action: 'Bet 20 (1/4 pot)', quality: 'mistake', explanation: 'Un bet piccolo non e credibile dopo aver puntato grosso per tre strade. Lavversario chiamera con quasi tutto. Se bluffi, sii coerente con il sizing.' },
    ],
  },
  {
    id: 'bl-06',
    category: 'bluff',
    difficulty: 'intermediate',
    title: 'Semi-bluff check-raise al flop',
    description: 'Avversario apre, tu chiami dal BB con T-9 di cuori. Flop: K-8-3 con due cuori. Avversario c-betta 5 in piatto di 11.',
    position: 'BB',
    holeCards: 'T♥ 9♥',
    board: 'K♣ 8♥ 3♥',
    potSize: 11,
    betToCall: 5,
    numPlayers: 2,
    actionHistory: 'Avversario apre, tu chiami dal BB. Flop K-8-3. Avversario c-betta 5.',
    options: [
      { action: 'Check-raise a 16', quality: 'best', explanation: 'Hai flush draw (9 outs) + gutshot (3 J non di cuori) = 12 outs = 45% con 2 carte. Il check-raise come semi-bluff e perfetto: puoi vincere subito o hai enorme equity se chiamato.' },
      { action: 'Call 5', quality: 'acceptable', explanation: 'Call e sicuro e profittevole con la tua equity. Ma il check-raise aggiunge fold equity e puo vincere il piatto immediatamente.' },
      { action: 'Fold', quality: 'mistake', explanation: 'Con un flush draw + gutshot hai troppa equity per foldare. 12 outs significa che vincerai quasi la meta delle volte.' },
    ],
  },

  // =====================================================================
  // BET SIZING (6 scenarios)
  // =====================================================================
  {
    id: 'bs-01',
    category: 'bet-sizing',
    difficulty: 'beginner',
    title: 'Sizing con top pair al flop',
    description: 'Hai AJ. Flop: J-8-3 rainbow. Sei in posizione. Piatto 12. Heads-up.',
    position: 'BTN',
    holeCards: 'A♣ J♥',
    board: 'J♦ 8♣ 3♠',
    potSize: 12,
    numPlayers: 2,
    actionHistory: 'Tu apri, avversario chiama. Flop J-8-3 rainbow. Avversario checka.',
    options: [
      { action: 'Bet 8 (2/3 pot)', quality: 'best', explanation: '2/3 pot e il sizing standard con top pair su board secco. Estrai valore da coppie medie e draw leggeri, mentre non rischi troppo se lavversario ha colpito piu forte.' },
      { action: 'Bet 4 (1/3 pot)', quality: 'acceptable', explanation: '1/3 pot estrae un po di valore ma lascia soldi sul tavolo. Con TPGK puoi permetterti un sizing piu grande.' },
      { action: 'Bet 12 (pot intero)', quality: 'acceptable', explanation: 'Pot intero e un po troppo: rischi di far foldare le mani che chiameranno 2/3 pot. Non serve puntare cosi tanto su un board secco.' },
      { action: 'Check', quality: 'mistake', explanation: 'Checkare top pair good kicker su un board secco e rinunciare a valore. Le mani peggiori non punteranno per te.' },
    ],
  },
  {
    id: 'bs-02',
    category: 'bet-sizing',
    difficulty: 'intermediate',
    title: 'Sizing su board con draw',
    description: 'Hai KK. Flop: Q-J-T con due cuori. Piatto 20. Avversario checka.',
    position: 'CO',
    holeCards: 'K♠ K♣',
    board: 'Q♥ J♥ T♦',
    potSize: 20,
    numPlayers: 2,
    actionHistory: 'Tu apri, avversario chiama. Flop Q-J-T. Avversario checka.',
    options: [
      { action: 'Bet 16 (circa 3/4 pot)', quality: 'best', explanation: 'Board super connesso con flush draw. DEVI puntare grosso per protezione! Con 3/4 pot rendi il call scorretto per flush draw e gutshot. Non dare carte gratis su questo board.' },
      { action: 'Bet 7 (1/3 pot)', quality: 'mistake', explanation: 'Troppo piccolo! Dai odds fenomenali a qualsiasi draw. Su board connessi come questo, il sizing piccolo e un errore di protezione.' },
      { action: 'Check', quality: 'mistake', explanation: 'Check su un board cosi pericoloso con un overpair e troppo passivo. Qualsiasi cuore, K, A, 8, 9 ti mette in difficolta.' },
      { action: 'All-in (overbet)', quality: 'acceptable', explanation: 'Un overbet o all-in non e terribile dato quanto e pericoloso il board, ma rischi di far foldare mani che pagheranno un bet piu piccolo.' },
    ],
    homeGameTip: 'Nei home game su board connessi punta SEMPRE grosso. I giocatori chiamano con qualsiasi draw: falli pagare caro!',
    isHomeGame: true,
  },
  {
    id: 'bs-03',
    category: 'bet-sizing',
    difficulty: 'advanced',
    title: 'River sizing con la nut',
    description: 'Hai il nut flush (Ah-Kh) su board con 3 cuori. River: 2s. Piatto 70. Avversario checka.',
    position: 'BTN',
    holeCards: 'A♥ K♥',
    board: 'J♥ 7♥ 3♣ 9♥ 2♠',
    potSize: 70,
    numPlayers: 2,
    actionHistory: 'Bet a ogni street, avversario chiama. River 2s. Avversario checka.',
    options: [
      { action: 'Bet 50 (circa 3/4 pot)', quality: 'best', explanation: 'Hai il nut flush. Il sizing di 3/4 pot massimizza il valore: lavversario con flush piu piccolo o set chiamera quasi sempre. Non troppo grande da spaventare, non troppo piccolo da perdere valore.' },
      { action: 'Bet 70 (pot)', quality: 'acceptable', explanation: 'Pot intero puo essere chiamato da flush piccoli ma fa foldare mani come set o due coppie. Un po troppo aggressivo.' },
      { action: 'Bet 20 (1/4 pot)', quality: 'mistake', explanation: 'Con il nut flush un bet cosi piccolo e un errore enorme. Lavversario con flush chiamera 3-4 volte tanto! Non regalare valore.' },
      { action: 'All-in', quality: 'acceptable', explanation: 'All-in puo funzionare se lavversario ha un flush medio, ma rischi di far foldare tutto tranne le mani piu forti.' },
    ],
  },
  {
    id: 'bs-04',
    category: 'bet-sizing',
    difficulty: 'beginner',
    title: 'C-bet sizing su board secco vs wet',
    description: 'Hai AK e hai aperto dal CO. BB chiama. Flop: A-7-2 rainbow. Piatto 12. BB checka.',
    position: 'CO',
    holeCards: 'A♠ K♦',
    board: 'A♣ 7♦ 2♠',
    potSize: 12,
    numPlayers: 2,
    actionHistory: 'Tu apri, BB chiama. Flop A-7-2 rainbow. BB checka.',
    options: [
      { action: 'Bet 4 (1/3 pot)', quality: 'best', explanation: 'Su un board secco come A-7-2, il bet piccolo e ideale. Non ci sono draw da cui proteggersi, e un bet piccolo estrae valore da coppie medie e A deboli senza spaventarli.' },
      { action: 'Bet 8 (2/3 pot)', quality: 'acceptable', explanation: '2/3 pot funziona ma puo far foldare mani che chiameranno 1/3. Su board secchi, il sizing piccolo e piu profittevole in media.' },
      { action: 'Bet 12 (pot)', quality: 'mistake', explanation: 'Pot intero su un board secco e troppo. Fai foldare tutto tranne le mani che ti battono o ti tengono testa. Non ha senso.' },
      { action: 'Check', quality: 'mistake', explanation: 'Checkare TPTK e lasciare soldi sul tavolo. Anche un bet piccolo estrae valore qui.' },
    ],
  },
  {
    id: 'bs-05',
    category: 'bet-sizing',
    difficulty: 'intermediate',
    title: 'Sizing di protezione con overpair',
    description: 'Hai QQ. Flop: J-9-8 con due fiori. Piatto 15. Avversario checka.',
    position: 'BTN',
    holeCards: 'Q♣ Q♦',
    board: 'J♣ 9♦ 8♣',
    potSize: 15,
    numPlayers: 2,
    actionHistory: 'Tu apri, avversario chiama. Flop J-9-8. Avversario checka.',
    options: [
      { action: 'Bet 12 (3/4 pot)', quality: 'best', explanation: 'Board pericolosissimo con flush draw e straight draw. QQ e vulnerabile! Il sizing grande e obbligatorio per protezione: forzi i draw a pagare caro o foldare.' },
      { action: 'Bet 5 (1/3 pot)', quality: 'mistake', explanation: 'Troppo poco! Su un board come J-9-8 con flush draw, un bet piccolo da odds perfette ai draw. Qualsiasi T, 7, 6, o carta di fiori ti mette in guai.' },
      { action: 'Check', quality: 'disaster', explanation: 'Checkare un overpair su un board cosi connesso e un regalo allavversario. Troppi turn spaventosi: quasi ogni carta cambia la dinamica.' },
    ],
  },
  {
    id: 'bs-06',
    category: 'bet-sizing',
    difficulty: 'advanced',
    title: 'Overbet al river come value',
    description: 'Hai il nut straight (AK su board Q-J-T-4-2). Lavversario ha chiamato flop e turn. Piatto 90. River 2.',
    position: 'BTN',
    holeCards: 'A♦ K♣',
    board: 'Q♠ J♥ T♦ 4♣ 2♠',
    potSize: 90,
    numPlayers: 2,
    actionHistory: 'Hai puntato flop e turn, avversario chiama sempre. River 2. Avversario checka.',
    options: [
      { action: 'Overbet: Bet 100 (piu del pot)', quality: 'best', explanation: 'Hai la nuts e lavversario ha chiaramente una mano forte (ha chiamato 2 strade). Un overbet estrae il massimo da set, due coppie, e flush miss che si trasformano in call disperati.' },
      { action: 'Bet 60 (2/3 pot)', quality: 'acceptable', explanation: '2/3 pot e un sizing ragionevole che verra chiamato quasi sempre. Ma con la nuts lasci valore che un overbet catturerebbe.' },
      { action: 'Bet 25 (circa 1/4 pot)', quality: 'mistake', explanation: 'Con la nuts un bet piccolo e un errore grave. Lavversario ha mostrato forza: fagliela pagare!' },
      { action: 'Check', quality: 'disaster', explanation: 'Checkare la nuts al river e il peggior errore possibile. Non puoi mai vincere di piu di cosi e stai regalando il piatto.' },
    ],
  },

  // =====================================================================
  // MULTI-WAY (8 scenarios)
  // =====================================================================
  {
    id: 'mw-01',
    category: 'multi-way',
    difficulty: 'beginner',
    title: 'Top pair in piatto multi-way',
    description: 'Hai AT. Flop: A-9-5 rainbow. 4 giocatori al flop. Piatto 20. Tutti checkano a te.',
    position: 'BTN',
    holeCards: 'A♦ T♣',
    board: 'A♠ 9♣ 5♦',
    potSize: 20,
    numPlayers: 4,
    actionHistory: '3 giocatori checkano a te al flop',
    options: [
      { action: 'Bet 14 (2/3 pot)', quality: 'best', explanation: 'In un piatto multi-way, top pair con buon kicker e una mano di valore. Punta per protezione e valore: con 3 avversari qualcuno ha probabilmente un pezzo del board.' },
      { action: 'Check', quality: 'acceptable', explanation: 'Checkare per pot control non e terribile in un piatto 4-way, ma perdi valore da mani come A-piccolo, 9-x, pocket pair.' },
      { action: 'Bet 5 (1/4 pot)', quality: 'mistake', explanation: 'Un bet piccolo in multi-way da odds troppo buone a 3 giocatori. Con 4 persone nel piatto, almeno uno chiamera sempre. Punta abbastanza per estrarre valore.' },
    ],
    homeGameTip: 'Nei home game i piatti multi-way sono frequentissimi. Top pair e ORO qui perche tutti hanno mani marginali. Punta e fatti pagare!',
    isHomeGame: true,
  },
  {
    id: 'mw-02',
    category: 'multi-way',
    difficulty: 'intermediate',
    title: 'Draw in piatto multi-way',
    description: 'Hai 8-7 suited. Flop: 6-5-K con un fiore del tuo colore. 5 giocatori. UTG punta 10 in piatto 25. 2 chiamano prima di te.',
    position: 'CO',
    holeCards: '8♠ 7♠',
    board: '6♣ 5♥ K♠',
    potSize: 55,
    betToCall: 10,
    numPlayers: 5,
    actionHistory: 'UTG punta 10. MP chiama. HJ chiama.',
    options: [
      { action: 'Call 10', quality: 'best', explanation: 'Hai OESD (8 outs per la scala) + backdoor flush. In un piatto multi-way le odds implicite sono enormi: se colpisci, 4 giocatori possono pagarti. Il call e obbligatorio.' },
      { action: 'Raise a 35', quality: 'mistake', explanation: 'Non raisare un draw in un piatto multi-way! Non farai foldare nessuno (troppi giocatori) e costruisci un piatto enorme con una mano che ha bisogno di migliorare.' },
      { action: 'Fold', quality: 'mistake', explanation: 'Con OESD e odds implicite enormi in un piatto 5-way, foldare e bruciare soldi. Le pot odds sono eccezionali: 10/55 = 18%.' },
    ],
    homeGameTip: 'I piatti multi-way nei home game sono il PARADISO per i draw: tanti giocatori = tanti soldi quando colpisci. Chiama con ogni draw ragionevole!',
    isHomeGame: true,
  },
  {
    id: 'mw-03',
    category: 'multi-way',
    difficulty: 'beginner',
    title: 'Overpair in piatto 3-way',
    description: 'Hai JJ. Flop: 9-7-4 rainbow. 3 giocatori. Tu sei stato il raiser preflop. Piatto 18. Tutti checkano a te.',
    position: 'CO',
    holeCards: 'J♣ J♦',
    board: '9♠ 7♣ 4♦',
    potSize: 18,
    numPlayers: 3,
    actionHistory: 'Tu apri, 2 chiamano. Flop 9-7-4. Entrambi checkano.',
    options: [
      { action: 'Bet 12 (2/3 pot)', quality: 'best', explanation: 'JJ e un forte overpair su un board medio-basso. Punta per valore e protezione. In un piatto 3-way non puoi permetterti di dare carte gratis: troppi draw possibili.' },
      { action: 'Bet 6 (1/3 pot)', quality: 'acceptable', explanation: 'Un bet piccolo in un piatto 3-way da troppo buon prezzo ai draw, ma almeno stai puntando. Con un overpair, preferisci un sizing piu grande.' },
      { action: 'Check', quality: 'mistake', explanation: 'Checkare un overpair in un piatto 3-way regala troppa equity ai draw. 8, 6, 5, T, Q possono tutte essere carte pericolose al turn.' },
    ],
  },
  {
    id: 'mw-04',
    category: 'multi-way',
    difficulty: 'intermediate',
    title: 'Bluff in piatto multi-way: si o no?',
    description: 'Hai A-5 (niente). Flop: K-Q-8 rainbow. 4 giocatori. Check a te. Piatto 20.',
    position: 'BTN',
    holeCards: 'A♣ 5♦',
    board: 'K♠ Q♣ 8♦',
    potSize: 20,
    numPlayers: 4,
    actionHistory: '3 giocatori checkano al flop',
    options: [
      { action: 'Check', quality: 'best', explanation: 'NON bluffare in piatti multi-way! Con 3 avversari, qualcuno ha quasi certamente un pezzo del board K-Q-8. Il bluff ha successo solo se TUTTI foldano, e con 3 giocatori e troppo improbabile.' },
      { action: 'Bet 7 (1/3 pot)', quality: 'mistake', explanation: 'Un bluff piccolo in multi-way e buttare soldi. Almeno un giocatore chiamera con Q-x, 8-x, o K-x. Non hai fold equity sufficiente.' },
      { action: 'Bet 15 (3/4 pot)', quality: 'disaster', explanation: 'Un bluff grande in multi-way e il modo piu veloce per bruciare il tuo stack. 3 giocatori, board alto: qualcuno ha qualcosa.' },
    ],
    homeGameTip: 'Regola doro per i home game: MAI bluffare in piatti con 3+ giocatori. I calling station non foldano e tu perdi soldi. Aspetta mani vere.',
    isHomeGame: true,
  },
  {
    id: 'mw-05',
    category: 'multi-way',
    difficulty: 'advanced',
    title: 'Set in piatto limpato multi-way',
    description: 'Piatto limpato con 5 giocatori. Hai 55 dal BB (check). Flop: 5-J-8 con due fiori. Piatto 10. UTG punta 5.',
    position: 'BB',
    holeCards: '5♦ 5♣',
    board: '5♥ J♣ 8♣',
    potSize: 10,
    numPlayers: 5,
    actionHistory: 'Piatto limpato 5-way. Flop 5-J-8. UTG punta 5.',
    options: [
      { action: 'Raise a 18', quality: 'best', explanation: 'Hai un set in un piatto multi-way su un board con flush draw. DEVI raisare per protezione! Con 4 avversari e un flush draw possibile, non puoi callare e sperare.' },
      { action: 'Call 5', quality: 'acceptable', explanation: 'Call e comprensibile per trappare, ma su un board con flush draw e 5 giocatori e troppo pericoloso. Un cuore al turn e potresti perdere un piatto enorme.' },
      { action: 'Fold', quality: 'disaster', explanation: 'Foldare un set al flop e... no. Mai. In nessuna circostanza.' },
    ],
    homeGameTip: 'Nei piatti limpati dei home game, quando colpisci un set RAISA SEMPRE. I giocatori con J-x o draw chiameranno felicemente.',
    isHomeGame: true,
  },
  {
    id: 'mw-06',
    category: 'multi-way',
    difficulty: 'beginner',
    title: 'Mano marginale in piatto limpato',
    description: 'Piatto limpato con 6 giocatori. Hai K-8o dal BB. Flop: K-T-6 con due cuori. Piatto 12. Check a te.',
    position: 'BB',
    holeCards: 'K♦ 8♣',
    board: 'K♠ T♥ 6♥',
    potSize: 12,
    numPlayers: 6,
    actionHistory: 'Piatto limpato 6-way. Flop K-T-6. Check a te.',
    options: [
      { action: 'Bet 8 (2/3 pot)', quality: 'acceptable', explanation: 'Puntare per scoprire dove ti trovi e ok, ma K-8 con kicker debole in un piatto 6-way e vulnerabile. Se qualcuno raisa o chiama, potresti essere dominato da KQ, KJ, KT.' },
      { action: 'Check', quality: 'best', explanation: 'Con K-8 in un piatto 6-way, il check e prudente. Il kicker debole ti mette in pericolo: se qualcuno ha K-migliore, perderai un piatto grosso. Meglio controllare e decidere al turn.' },
      { action: 'Bet 3 (1/4 pot)', quality: 'acceptable', explanation: 'Un bet piccolo puo funzionare come probe, ma non ti da molte informazioni in un piatto 6-way.' },
    ],
    homeGameTip: 'Nei home game con piatti limpati, K con kicker debole e una trappola. Tutti giocano K-qualcosa e il tuo kicker perde spesso. Cautela!',
    isHomeGame: true,
  },
  {
    id: 'mw-07',
    category: 'multi-way',
    difficulty: 'intermediate',
    title: 'Nuts in piatto multi-way al turn',
    description: 'Hai A-2 di cuori. Board: K-7-4-9 con tre cuori (flush al turn!). 4 giocatori. UTG punta 15 in piatto di 30. MP chiama.',
    position: 'CO',
    holeCards: 'A♥ 2♥',
    board: 'K♥ 7♣ 4♥ 9♥',
    potSize: 60,
    numPlayers: 4,
    actionHistory: 'UTG punta 15, MP chiama. Tocca a te.',
    options: [
      { action: 'Raise a 50', quality: 'best', explanation: 'Hai il nut flush! In un piatto multi-way devi raisare per valore: ci sono altri giocatori che possono avere flush piu piccoli o set. Costruisci il piatto al massimo!' },
      { action: 'Call 15', quality: 'acceptable', explanation: 'Call per trappare e unidea, ma in un piatto multi-way perdi troppo valore. Se tutti checkano al river, hai perso unopportunita enorme. Con la nuts, raisa!' },
      { action: 'All-in', quality: 'acceptable', explanation: 'All-in con la nuts e aggressivo ma in un piatto multi-way puo funzionare se qualcuno ha un flush inferiore o set.' },
    ],
  },
  {
    id: 'mw-08',
    category: 'multi-way',
    difficulty: 'advanced',
    title: 'Continuation bet in piatto 3-way',
    description: 'Hai aperto con AJ dal CO. BTN e BB chiamano. Flop: T-7-3 rainbow. BB checka. Piatto 18. 3-way.',
    position: 'CO',
    holeCards: 'A♣ J♥',
    board: 'T♦ 7♣ 3♠',
    potSize: 18,
    numPlayers: 3,
    actionHistory: 'Tu apri CO, BTN e BB chiamano. Flop T-7-3. BB checka.',
    options: [
      { action: 'Check', quality: 'best', explanation: 'In un piatto 3-way su un board medio, la c-bet con AJ high e sconsigliata. Hai due avversari e nessuno ha il board. Qualcuno probabilmente ha una coppia. Check e aspetta il turn.' },
      { action: 'Bet 6 (1/3 pot)', quality: 'acceptable', explanation: 'Un bet piccolo come c-bet non e terribile ma in 3-way la fold equity e bassa. Uno dei due chiamera quasi sempre con coppia di T, 7, o pocket.' },
      { action: 'Bet 14 (3/4 pot)', quality: 'mistake', explanation: 'Un c-bet grosso in un piatto 3-way senza aver colpito e bruciare chip. Devi essere piu selettivo con le c-bet quando ci sono piu avversari.' },
    ],
  },

  // =====================================================================
  // POSITION (6 scenarios)
  // =====================================================================
  {
    id: 'pos-01',
    category: 'position',
    difficulty: 'beginner',
    title: 'Vantaggio di posizione al flop',
    description: 'Hai JTs in posizione (BTN). Avversario (BB) checka al flop: Q-8-4 con un fiore del tuo colore. Piatto 12.',
    position: 'BTN',
    holeCards: 'J♣ T♣',
    board: 'Q♦ 8♣ 4♣',
    potSize: 12,
    numPlayers: 2,
    actionHistory: 'Tu apri BTN, BB chiama. Flop Q-8-4. BB checka.',
    options: [
      { action: 'Bet 4 (1/3 pot)', quality: 'best', explanation: 'In posizione con backdoor flush draw + gutshot, un c-bet piccolo e perfetto. Lavversario non sa se hai la Q e foldera spesso. Il vantaggio di posizione ti permette di controllare la narrazione.' },
      { action: 'Check', quality: 'acceptable', explanation: 'Check per vedere una carta gratis e ok: hai outs per migliorare. Ma perdi lopportunita di vincere il piatto subito con un bet piccolo.' },
      { action: 'Bet 10 (quasi pot)', quality: 'mistake', explanation: 'Troppo grosso per un bluff con poca equity. In posizione puoi permetterti un sizing piccolo perche controlli il piatto.' },
    ],
  },
  {
    id: 'pos-02',
    category: 'position',
    difficulty: 'intermediate',
    title: 'Fuori posizione con mano forte',
    description: 'Hai AQ dal BB. Hai 3-bettato e il BTN ha chiamato. Flop: A-9-4 rainbow. Piatto 30. Sei fuori posizione.',
    position: 'BB',
    holeCards: 'A♣ Q♦',
    board: 'A♠ 9♣ 4♦',
    potSize: 30,
    numPlayers: 2,
    actionHistory: 'Tu 3-bet dal BB, BTN chiama. Flop A-9-4 rainbow.',
    options: [
      { action: 'Bet 10 (1/3 pot)', quality: 'best', explanation: 'Fuori posizione con TPTK, punta per valore con un sizing piccolo. Questo sizing funziona bene perche proteggi la tua mano e mantieni il piatto gestibile fuori posizione.' },
      { action: 'Bet 22 (3/4 pot)', quality: 'acceptable', explanation: 'Un bet grande estrae valore ma rende il piatto troppo grande fuori posizione. Se lavversario raisa, sei in una situazione scomoda.' },
      { action: 'Check', quality: 'acceptable', explanation: 'Check per trappare e unidea legittima con TPTK fuori posizione. Lavversario potrebbe puntare con bluff. Ma rischi di perdere valore se checka dietro.' },
    ],
  },
  {
    id: 'pos-03',
    category: 'position',
    difficulty: 'beginner',
    title: 'Late position steal',
    description: 'Tavolo 6-max. Tutti foldano fino a te sul CO. Hai Q-9 suited. Blinds 1/2.',
    position: 'CO',
    holeCards: 'Q♦ 9♦',
    numPlayers: 6,
    actionHistory: 'UTG fold, MP fold',
    options: [
      { action: 'Raise a 2.5x (5)', quality: 'best', explanation: 'Q9s dal CO con tutti fold e un raise automatico. Hai posizione su chi chiama, buona giocabilita postflop, e i blinds foldano la maggior parte delle mani.' },
      { action: 'Fold', quality: 'mistake', explanation: 'Troppo tight! Dal CO in late position, Q9s e ampiamente nel range di apertura. Non sprecare questa posizione favorevole.' },
      { action: 'Limp (call 2)', quality: 'mistake', explanation: 'Limpare in late position e sempre un errore: perdi liniziativa e mostri debolezza. Raise o fold, mai limp.' },
    ],
  },
  {
    id: 'pos-04',
    category: 'position',
    difficulty: 'intermediate',
    title: 'Pot control fuori posizione',
    description: 'Hai KJ dal BB. Board al turn: K-T-5-8. Hai chiamato preflop e c-bettato al flop, avversario ha chiamato. Piatto 40. Sei OOP.',
    position: 'BB',
    holeCards: 'K♠ J♣',
    board: 'K♦ T♣ 5♠ 8♥',
    potSize: 40,
    numPlayers: 2,
    actionHistory: 'Flop: tu puntata, avversario chiama. Turn: 8.',
    options: [
      { action: 'Check', quality: 'best', explanation: 'Fuori posizione con top pair kicker medio, il check al turn e pot control ottimale. Lavversario potrebbe avere KQ, AK, o un set. Controllando il piatto limiti le perdite quando sei battuto.' },
      { action: 'Bet 20 (1/2 pot)', quality: 'acceptable', explanation: 'Puntare per valore e ragionevole, ma fuori posizione con KJ rischi: se raisa sei in guai seri. Il check e piu sicuro.' },
      { action: 'Bet 35 (quasi pot)', quality: 'mistake', explanation: 'Puntare grosso al turn OOP con top pair kicker medio e over-committarti. Se lavversario raisa, hai un problema enorme.' },
    ],
  },
  {
    id: 'pos-05',
    category: 'position',
    difficulty: 'advanced',
    title: 'Floating in posizione',
    description: 'Avversario apre da UTG e c-betta al flop: 9-6-2 rainbow. Hai A-5s sul BTN. Tu hai chiamato preflop. Piatto 18, avversario punta 6.',
    position: 'BTN',
    holeCards: 'A♠ 5♠',
    board: '9♦ 6♣ 2♠',
    potSize: 18,
    betToCall: 6,
    numPlayers: 2,
    actionHistory: 'UTG apre, tu chiami BTN. Flop 9-6-2. UTG c-betta 6.',
    options: [
      { action: 'Call 6 (float)', quality: 'best', explanation: 'Il float in posizione e una giocata avanzata. Chiami la c-bet leggera per prendere il piatto al turn quando lavversario checka (e checkera spesso senza niente). La posizione ti da il controllo.' },
      { action: 'Fold', quality: 'acceptable', explanation: 'Fold e ok se non ti senti a tuo agio con il float. Ma con A-alto e posizione, stai rinunciando a molte situazioni profittevoli al turn.' },
      { action: 'Raise a 18', quality: 'acceptable', explanation: 'Un raise funziona come bluff ma ti impegna di piu. Il float e piu flessibile: se il turn e brutto puoi arrenderti con meno investito.' },
    ],
  },
  {
    id: 'pos-06',
    category: 'position',
    difficulty: 'advanced',
    title: 'Donk bet dal big blind',
    description: 'Avversario apre dal BTN, tu chiami con 7-6s dal BB. Flop: 8-5-3 rainbow (hai OESD). Piatto 12. Sei primo a parlare.',
    position: 'BB',
    holeCards: '7♠ 6♠',
    board: '8♦ 5♣ 3♠',
    potSize: 12,
    numPlayers: 2,
    actionHistory: 'BTN apre, tu chiami dal BB. Flop 8-5-3.',
    options: [
      { action: 'Check (poi decide)', quality: 'best', explanation: 'Anche con un OESD, il check e migliore della donk bet. Se lavversario c-betta, puoi check-raisare come semi-bluff. Se checka, vedi il turn gratis. La donk bet rinuncia a queste opzioni.' },
      { action: 'Donk bet 8 (2/3 pot)', quality: 'acceptable', explanation: 'La donk bet puo funzionare come semi-bluff ma e meno efficiente del check-raise. Lavversario avrebbe spesso c-bettato, dandoti lopportunita del check-raise.' },
      { action: 'Donk bet 4 (1/3 pot)', quality: 'mistake', explanation: 'Una donk bet piccola non ha senso: non fa foldare niente e non costruisce il piatto abbastanza per i tuoi draw.' },
    ],
  },

  // =====================================================================
  // HOME GAME SPECIFIC (additional scenarios with isHomeGame)
  // =====================================================================
  {
    id: 'hg-01',
    category: 'preflop-opening',
    difficulty: 'beginner',
    title: 'Piatto limpato al home game',
    description: 'Home game tipico: 3 giocatori limpano davanti a te. Sei in CO con K-J suited. Blinds 0.25/0.50.',
    position: 'CO',
    holeCards: 'K♠ J♠',
    numPlayers: 6,
    potSize: 2.5,
    actionHistory: 'UTG limpa, MP limpa, HJ limpa',
    options: [
      { action: 'Raise a 4x + 1 per limper (5)', quality: 'best', explanation: 'Nei home game con tanti limper, KJs e abbastanza forte per isolare. Raisa grande per ridurre il campo. Formula: 3-4x + 1x per limper. Vuoi giocare contro 1-2 giocatori, non 5.' },
      { action: 'Limp (call 0.50)', quality: 'acceptable', explanation: 'Limpare per vedere un flop economico non e terribile in un home game, ma perdi liniziativa e giocherai un piatto multi-way caotico.' },
      { action: 'Raise a 2x (1)', quality: 'mistake', explanation: 'Un raise troppo piccolo con 3 limper gia dentro non fara foldare nessuno. Chiameranno tutti e ti ritroverai nel piatto multi-way che volevi evitare.' },
      { action: 'Fold', quality: 'disaster', explanation: 'Foldare KJs con 3 limper deboli? Hai una mano forte e posizione. Questa e unopportunita doro per vincere un piatto grosso.' },
    ],
    homeGameTip: 'Al home game la regola e: raisa GRANDE sopra i limper. I giocatori chiamano con tutto, quindi sfrutta la tua mano migliore con sizing aggressivo.',
    isHomeGame: true,
  },
  {
    id: 'hg-02',
    category: 'value-bet',
    difficulty: 'beginner',
    title: 'Value bet al river contro calling station',
    description: 'Home game. Hai A-K, board: A-9-4-2-7 rainbow. Piatto 30. Lavversario e un noto calling station.',
    position: 'BTN',
    holeCards: 'A♦ K♠',
    board: 'A♣ 9♦ 4♠ 2♥ 7♣',
    potSize: 30,
    numPlayers: 2,
    actionHistory: 'Hai puntato flop e turn. River 7. Avversario checka.',
    options: [
      { action: 'Bet 25 (quasi pot)', quality: 'best', explanation: 'Contro un calling station, punta GROSSO per valore! Chiamera con qualsiasi Asso, coppia media, perfino K alto. Non aver paura di puntare tanto: e quello che li rende calling station.' },
      { action: 'Bet 10 (1/3 pot)', quality: 'acceptable', explanation: 'Un bet piccolo verra chiamato ma lasci soldi sul tavolo. Il calling station chiamera 25 altrettanto facilmente quanto chiama 10.' },
      { action: 'Check', quality: 'mistake', explanation: 'Non checkare per valore contro un calling station! Lunica volta che i calling station ti danno soldi e quando punti. Checkando regali un piatto che potresti ingrandire.' },
    ],
    homeGameTip: 'Contro i calling station: punta SEMPRE per valore, punta GROSSO, non bluffare MAI. Loro pagano: fatti pagare al massimo!',
    isHomeGame: true,
  },
  {
    id: 'hg-03',
    category: 'bluff',
    difficulty: 'intermediate',
    title: 'Tentazione di bluffare al home game',
    description: 'Home game. Hai 6-4 (niente). Board: K-Q-J-8-3. 3 giocatori nel piatto. Piatto 40. Check a te.',
    position: 'BTN',
    holeCards: '6♣ 4♦',
    board: 'K♠ Q♥ J♣ 8♦ 3♠',
    potSize: 40,
    numPlayers: 3,
    actionHistory: 'Piatto limpato. River 3. 2 giocatori checkano a te.',
    options: [
      { action: 'Check', quality: 'best', explanation: 'Al home game NON bluffare in piatti multi-way! Almeno uno dei due avversari ha un pezzo del board K-Q-J. Risparmia i tuoi chip per quando hai una mano vera.' },
      { action: 'Bet 10 (1/4 pot)', quality: 'mistake', explanation: 'Anche un bluff piccolo e buttare soldi contro giocatori che non foldano. Al home game i bluff funzionano raramente, specialmente multi-way.' },
      { action: 'Bet 35 (quasi pot)', quality: 'disaster', explanation: 'Un bluff enorme in un piatto multi-way al home game e il modo migliore per perdere tutto il tuo stack in una sera. Non farlo.' },
    ],
    homeGameTip: 'Regola #1 del home game: NON BLUFFARE. I giocatori chiamano con tutto. Risparmia i bluff per i tavoli online o i tornei.',
    isHomeGame: true,
  },
  {
    id: 'hg-04',
    category: 'multi-way',
    difficulty: 'beginner',
    title: 'Piatto limpato: quando raisi dal BB',
    description: 'Home game. 4 giocatori limpano. Sei nel BB con Q-Q. Piatto 5 (con i blind). Blinds 0.50/1.',
    position: 'BB',
    holeCards: 'Q♣ Q♠',
    numPlayers: 6,
    potSize: 5.5,
    actionHistory: 'UTG limpa, MP limpa, CO limpa, BTN limpa',
    options: [
      { action: 'Raise a 7x (7)', quality: 'best', explanation: 'QQ nel BB con 4 limper: DEVI raisare grosso! Il sizing deve essere enorme perche al home game i limper chiamano quasi tutto. 6-7x + extra per i limper. Vuoi isolare e giocare per stack.' },
      { action: 'Raise a 3x (3)', quality: 'mistake', explanation: 'Troppo poco! Al home game 3x con 4 limper non fara foldare nessuno. Finira in un piatto 5-way dove QQ e vulnerabile.' },
      { action: 'Check', quality: 'disaster', explanation: 'Check con QQ nel BB e criminale. Giocherai un piatto 5-way senza iniziativa e qualsiasi A, K al flop ti mettera in difficolta.' },
    ],
    homeGameTip: 'Nei home game con limper, raisa 5-7x con le mani premium. Se chiamano? Meglio! Hai la mano migliore e un piatto enorme.',
    isHomeGame: true,
  },
  {
    id: 'hg-05',
    category: 'position',
    difficulty: 'intermediate',
    title: 'Giocare pocket pair in piatto limpato',
    description: 'Home game. 3 limper. Tu sei sul BTN con 8-8. Blinds 0.50/1.',
    position: 'BTN',
    holeCards: '8♦ 8♠',
    numPlayers: 6,
    potSize: 4.5,
    actionHistory: 'UTG limpa, HJ limpa, CO limpa',
    options: [
      { action: 'Raise a 6 (6x)', quality: 'best', explanation: '88 in posizione con 3 limper: raisa per isolare! Vuoi giocare contro 1-2 giocatori dove il tuo 88 ha piu equity. Se colpisci il set in un piatto raisato, vinci un piatto enorme.' },
      { action: 'Call (limp)', quality: 'acceptable', explanation: 'Limpare per set mining e ok nei home game: tanti giocatori = odds implicite enormi se colpisci il set. Ma il raise e superiore perche prendi liniziativa.' },
      { action: 'Fold', quality: 'disaster', explanation: 'Foldare 88 in posizione con 3 limper deboli? Assolutamente no. Hai una mano decente e posizione perfetta.' },
    ],
    homeGameTip: 'Al home game con pocket pair medio: raisa per isolare oppure limpa per set mining. Entrambe funzionano, ma il raise e piu profittevole a lungo termine.',
    isHomeGame: true,
  },
  {
    id: 'hg-06',
    category: 'bet-sizing',
    difficulty: 'intermediate',
    title: 'Sizing contro chi chiama troppo',
    description: 'Home game. Hai K-K. Flop: K-7-3 rainbow. Avversario noto per chiamare tutto. Piatto 20.',
    position: 'CO',
    holeCards: 'K♥ K♦',
    board: 'K♣ 7♠ 3♦',
    potSize: 20,
    numPlayers: 2,
    actionHistory: 'Tu apri, calling station chiama. Flop K-7-3. Avversario checka.',
    options: [
      { action: 'Bet 16 (3/4 pot)', quality: 'best', explanation: 'Contro un calling station con top set, punta GROSSO! Chiamera con qualsiasi coppia, qualsiasi draw, K-basso, anche A-alto. Estrai il massimo valore dal suo errore di chiamare troppo.' },
      { action: 'Bet 7 (1/3 pot)', quality: 'acceptable', explanation: 'Anche un bet piccolo verra chiamato, ma perdi tantissimo valore. Il calling station chiamera 16 con la stessa facilita con cui chiama 7.' },
      { action: 'Check (slowplay)', quality: 'mistake', explanation: 'Non slowplayare contro un calling station! Lui paga QUALSIASI bet. Checkando gli regali una carta gratis che potrebbe farti perdere il piatto.' },
    ],
    homeGameTip: 'Contro i calling station, sizing = piu grande possibile senza farli foldare. Al home game, il piu grande possibile e spesso il pot intero!',
    isHomeGame: true,
  },
  {
    id: 'hg-07',
    category: 'facing-raise',
    difficulty: 'beginner',
    title: 'Home game: tutti raisano - tu cosa fai?',
    description: 'Home game. UTG raisa a 3x, MP chiama, CO chiama. Sei sul BTN con A-T offsuit. Blinds 0.50/1.',
    position: 'BTN',
    holeCards: 'A♣ T♦',
    numPlayers: 6,
    potSize: 10.5,
    betToCall: 3,
    actionHistory: 'UTG raise a 3, MP chiama, CO chiama',
    options: [
      { action: 'Call 3', quality: 'best', explanation: 'ATo in posizione con ottime odds (3 in un piatto di 10.5) e un call facile. Hai posizione su tutti e se colpisci top pair, puoi vincere un piatto grosso multi-way.' },
      { action: 'Fold', quality: 'acceptable', explanation: 'Fold non e terribile: ATo fuori posizione o senza odds e un fold. Ma qui hai posizione e odds 3.5:1, quindi il call e migliore.' },
      { action: '3-bet a 12', quality: 'mistake', explanation: 'Un 3-bet con AT in un piatto gia multi-way non ha senso: non farai foldare nessuno (3 giocatori gia dentro) e sarai out of position contro un range forte.' },
    ],
    homeGameTip: 'Al home game con piatti raisati multi-way, chiama in posizione con mani decenti. Le odds implicite sono enormi quando colpisci.',
    isHomeGame: true,
  },
  {
    id: 'hg-08',
    category: 'draw-play',
    difficulty: 'beginner',
    title: 'Home game: flush draw in piatto multi-way',
    description: 'Home game. 5 giocatori al flop limpato. Hai 9-7 di cuori. Flop: K-4-2 con due cuori. Piatto 5. UTG punta 2.',
    position: 'CO',
    holeCards: '9♥ 7♥',
    board: 'K♣ 4♥ 2♥',
    potSize: 5,
    betToCall: 2,
    numPlayers: 5,
    actionHistory: 'Piatto limpato 5-way. Flop K-4-2. UTG punta 2. MP chiama.',
    options: [
      { action: 'Call 2', quality: 'best', explanation: 'Flush draw in un piatto multi-way con odds incredibili: 2 da chiamare in un piatto di 9+. Hai 9 outs e le odds implicite sono enormi con 5 giocatori. Call automatico!' },
      { action: 'Raise a 8', quality: 'mistake', explanation: 'Non raisare un flush draw in un piatto multi-way al home game! Nessuno foldera e costruirai un piatto enorme con una mano incompleta. Chiama e spera di colpire.' },
      { action: 'Fold', quality: 'disaster', explanation: 'Foldare un flush draw con queste odds e buttare soldi dalla finestra. 2 in un piatto di 9 con 9 outs? Il call e automatico.' },
    ],
    homeGameTip: 'Nei piatti multi-way dei home game, i flush draw sono miniere doro. Le odds implicite sono enormi perche tutti chiamano anche quando il flush e ovvio!',
    isHomeGame: true,
  },
];

// === UTILITY FUNCTIONS ===

export function getScenariosByCategory(category: ScenarioCategory): Scenario[] {
  return SCENARIOS.filter(s => s.category === category);
}

export function getScenariosByDifficulty(difficulty: Difficulty): Scenario[] {
  return SCENARIOS.filter(s => s.difficulty === difficulty);
}

export function getHomeGameScenarios(): Scenario[] {
  return SCENARIOS.filter(s => s.isHomeGame === true);
}
